-
  get:
    route: 'groups/:identifier'
    command: show_groups
    params: '*identifier'
    description: Returns a specific identifier from the provided identifier
-
  post:
    route: 'groups'
    command: create_groups
    params: '*description'
    description: Create a group

#user routes
-
  post:
    route: 'groups/:group_id/users'
    command: create_users
    params: '*group_id, *name, *amount_payed_cents, email, description'
    description: Create user in a group
-
  get:
    route: 'groups/:group_id/users'
    command: list_users
    params: '*group_id'
-
  delete:
    route: 'users/:user_id'
    command: delete_users
    params: '*user_id'
    description: remove a user
-
  put:
    route: 'users/:user_id'
    command: update_users
    params: '*user_id, *name, *amount_payed_cents, email, description'
    description: update a user

#comments routes
-
  post:
    route: 'groups/:group_id/comments'
    command: create_comments
    params: '*group_id, *name, description'
    description: Create comment in a group
-
  get:
    route: 'groups/:group_id/comments'
    command: list_by_group_comments
    params: '*group_id'
-
  delete:
    route: 'comments/:comment_id'
    command: delete_comments
    params: '*comments_id'
    description: remove a comment

#line items
-
  post:
    route: 'users/:user_id/line_items'
    command: create_line_items
    params: '*user_id, *name, *amount_in_cents'
    description: Create line item for a user
-
  delete:
    route: 'line_items/:line_item_id'
    command: delete_line_items
    params: '*line_item_id'
    description: remove a line_item
